### ISSUE TITLE
Npm audit vulnerability

### ISSUE THREAD

**Issue by adilsonfsantos** [mbalabash/gulp-sqip#1]
Hello, just wanted to let you know, that js-yaml is vulnerable to [Denial of Service](https://npmjs.com/advisories/788 ) and [Code injection](https://npmjs.com/advisories/813 ) attacks with a high severity.

Any plans on resolving this?

**Comment by mbalabash** [comment]
Hi @adilsonfsantos 
Sorry for slow response. I will fix this issue in next day.

But I also suggests you to look on a new version of [sqip](https://github.com/axe312ger/sqip).
Now it could runs from npm script and doesn't require additional dependencies as **go** and **primitives** (if you run it on 64bit OS).

**Comment by adilsonfsantos** [comment]
Thanks for the answer, I already knew about [sqip](https://github.com/axe312ger/sqip) but I couldn't implement in my gulp workflow.
So I found your project.

**Comment by mbalabash** [comment]
Ok. This error is not in `gulp-sqip` module. 
It's in [sqip/legacy](https://github.com/axe312ger/sqip/blob/legacy/package.json) module because of **"svgo": "^0.7.2"**.

So, you can file issue in origin project. And when it will fix this error should disappear.
